InventoryApp/InventoryApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenVerifyView, TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("shop.urls",namespace="shop"),name="shop"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/', include('api.urls')),
    path('api/v2/', include('InventoryApp.routers')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    

InventoryApp/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken.views import obtain_auth_token
from . import views
urlpatterns = [
    path("create-stock/",views.StockCreateView.as_view(),name="create-stock-api"),
    path("list-stock/",views.StockListView.as_view(),name="list-stock-api"),
    path("update-stock/<int:pk>/",views.StockUpdateView.as_view(),name="update-stock-api"),
    path("delete-stock/<int:pk>/",views.StockDeleteView.as_view(),name="delete-stock-api"),
    path("auth/",obtain_auth_token),
    
]
urlpatterns = format_suffix_patterns(urlpatterns)

InventoryApp/shop/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = "shop"

urlpatterns =[
    path("",views.IndexView.as_view(),name="index"),
    path("list-page/",views.StockList.as_view(),name="list-page"),
    path("dashboard/",views.Dashboard.as_view(),name="dashboard"),
    path("detail-page/<int:pk>/",views.StockDetail.as_view(),name="detail-page"),
    path("update/<int:pk>/",views.StockUpdate.as_view(),name="update-page"),
    path("form-page/",views.StockCreate.as_view(),name="form-page"),

    path('pdf/', views.Pdfs.as_view(),name="pdfs"),

    path('login/', auth_views.LoginView.as_view(),name="login"),
    path("logout/",views.StockLogout,name="logout-page"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
htmx_urlpatterns = [
    path("search/",views.search_product,name="search-product"),
    path("timer/",views.Timer.as_view(),name="base-html"),
]
urlpatterns += htmx_urlpatterns


InventoryApp/templates/partials/nav-links.html
<nav>
    <ul>
        <li><a href="{% url 'shop:form-page' %}">FORM</a></li>
        <li><a href="{% url 'shop:list-page' %}">LIST-STOCk</a></li>
        <li><a href="{% url 'shop:pdfs' %}">PDF</a></li>
    </ul>
</nav>

InventoryApp/templates/partials/pdfs.html

{% extends "shop/base.html" %}


{% block main %}

{% if obj  %}
<style>
    thead,tbody{
        width: 100%;
    }
    td{
        margin: auto;
        text-align: left;
        text-decoration: none;
        width: 200px;
    }
</style>
<table>
    <thead>
        <tr>
            <td>#</td>
            <td>product Name</td>
            <td>document link</td>
        </tr>
    </thead>

    <tbody>
        {% for items in obj %}

        <tr>
            <td style="width: 10px; padding-left: 0;">{{forloop.counter}}</td>
            <td style="width: 10px;">{{items.product_name}}</td>
            {% if items.docs %}
            <td> <a href="{{items.docs.url}}">Download</a> </td>
            {% else %}
            <td>No doc</td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endif %}


{% endblock main %}


InventoryApp/templates/partials/search-results.html

{% load static %}


<table>
    <style>
        table{
            width: 100%;
            border: 2px solid #fff;
        }
        thead{
            width: 100%;
            height: 8vh;
            border: 1px dotted pink;
        }
        thead tr td{
            width: 200px;
            height: 20px;
            text-align: left;
        }
        tbody tr{
            display: flex;
            width: 100%;
            justify-content: space-around;
            align-items: center;
            margin: auto;
        }
        tbody tr td{
            width: 200px;
            height: 20px;
            text-align: left;
        }

    </style>
    <thead>
        <tr>
            <td>Product Name</td>
            <td>Net weight</td>
            <td>Quantity</td>
            <td>Date</td>
            <td>Isle</td>
            <td>Tags</td>
            <td>Isle</td>
            <td>Tags</td>
            <td>Storage</td>
            <td>Shelf Life</td>
            <td>Expirary</td>
            <td>Attendant</td>
            <td>Status</td>
            <td>Docs</td>
        </tr>
    </thead>
    {% if q_results %}
    {% for q_result in q_results %}
    <tr>
        <td>{{q_result.product_name}}</td>
        <td>{{q_result.net_weight}}</td>
        <td>{{q_result.qty}}</td>
        <td>{{q_result.date}}</td>
        <td>{{q_result.isle}}</td>
        <td>{{q_result.tags}}</td>
        <td>{{q_result.storage}}</td>
        <td>{{q_result.shelf_life}}</td>
        <td>{{q_result.attendant}}</td>
        <td>{{q_result.status}}</td>
        {% if q_result.docs.url %}
        <td><a href="{{q_result.docs.url}}">Download</a></td>
        {% else %}
        <td><p>Noe docs</p></td>
        {% endif %}
        {% endfor %}
    </tr>
</table>
{% else %}
<p>No results</p>
{% endif %}

InventoryApp/templates/partials/search.html

{% load static %}
<div class="indicator">
    <style>
        .indicator{
            width: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

    </style>
    <span class="htmx-indicator">
        <img src="{% static 'img/favicon-16x16.png' %}" /> Searching...
    </span>
</div>
<div class="search">
    {% csrf_token %}
    <form>
        <label for="productname">Name</label>
        <input type="text" name="name" id="" hx-post="{% url 'shop:search-product' %}"
            hx-trigger="keyup changed:500ms" hx-indicator=".htmx-indicator" hx-push-url="true"
            hx-target="#search-results"
            placeholder="search for product name">
    </form>
</div>
<div id="search-results" class="search-results">


</div>

InventoryApp/templates/partials/timer-tag.html
<h3>Time | {% now "D M Y H T " %} |</h3>