InventoryApp/InventoryApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenVerifyView, TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("shop.urls",namespace="shop"),name="shop"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/', include('api.urls')),
    path('api/v2/', include('InventoryApp.routers')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    

InventoryApp/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken.views import obtain_auth_token
from . import views
urlpatterns = [
    path("create-stock/",views.StockCreateView.as_view(),name="create-stock-api"),
    path("list-stock/",views.StockListView.as_view(),name="list-stock-api"),
    path("update-stock/<int:pk>/",views.StockUpdateView.as_view(),name="update-stock-api"),
    path("delete-stock/<int:pk>/",views.StockDeleteView.as_view(),name="delete-stock-api"),
    path("auth/",obtain_auth_token),
    
]
urlpatterns = format_suffix_patterns(urlpatterns)

InventoryApp/shop/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = "shop"

urlpatterns =[
    path("",views.IndexView.as_view(),name="index"),
    path("list-page/",views.StockList.as_view(),name="list-page"),
    path("dashboard/",views.Dashboard.as_view(),name="dashboard"),
    path("detail-page/<int:pk>/",views.StockDetail.as_view(),name="detail-page"),
    path("update/<int:pk>/",views.StockUpdate.as_view(),name="update-page"),
    path("form-page/",views.StockCreate.as_view(),name="form-page"),

    path('pdf/', views.Pdfs.as_view(),name="pdfs"),

    path('login/', auth_views.LoginView.as_view(),name="login"),
    path("logout/",views.StockLogout,name="logout-page"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
htmx_urlpatterns = [
    path("search/",views.search_product,name="search-product"),
    path("timer/",views.Timer.as_view(),name="base-html"),
]
urlpatterns += htmx_urlpatterns


InventoryApp/shop/models.py

from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.




class Stock(models.Model):
    tags =[
        ("cereals", "cereals"),
        ("flour", "flour"),
        ("dairy", "dairy"),
        ("oil", "oil"),
    ]
    storage =[
        ("freezer", "freezer"),
        ("dry", "dry"),
        ("low", "low"),
        ("canned", "canned"),
    ]
    ISLE = [
        ("one",1),
        ("two",2),
        ("three",3),
        ("four",4),
        ("five",5),
    ]
    product_name = models.CharField(verbose_name="product name",max_length=100)
    net_weight = models.PositiveIntegerField(verbose_name="weight in tonnes")
    qty = models.PositiveIntegerField(verbose_name="quantity")
    date = models.DateField(verbose_name="date of stock",auto_created=True,auto_now_add=True)
    isle = models.CharField(verbose_name="shelf no:",max_length=5,choices=ISLE,default=[0][0])
    tags = models.CharField(verbose_name="select tag",max_length=50,choices=tags)
    storage = models.CharField(verbose_name="storage conditions",max_length=50,choices=storage)
    shelf_life = models.DurationField(null=True)
    exp = models.DateField(verbose_name="Expiry date",null=True)
    attendant = models.ForeignKey(to=User,related_name="handler",on_delete = models.CASCADE,verbose_name="handler",default=1)
    status = models.CharField(verbose_name="comment",max_length=25,null=True)
  

    # @property
    # def Url(self):
    #     if self.docs == "":
    #         self.docs= ""
    #     return self.docs

    def __str__(self) -> str:
        return f"{self.product_name}"
    
    @classmethod
    def company(cls):
        return cls.company

    @staticmethod
    def get_date():
        return datetime.today()
    
    class Meta:
        permissions =[
            ("can_allow_dispatch", "can allow dispatch"),
            ("can_make_reorders", "can make new orders"),
        ]
        ordering = ["product_name","-date"]
    
    def get_absolute_url(self):
        return reverse("shop:detail-page",kwargs={"pk":self.pk})

class Sales(models.Model):
    employee = models.ForeignKey(User,on_delete=models.CASCADE,related_name="seller",verbose_name="attendant")
    stock_sold = models.ForeignKey(Stock,on_delete=models.CASCADE,related_name="item",verbose_name="Stock sold")
    stock_qty = models.PositiveIntegerField(verbose_name="quantity sold")
    date = models.DateTimeField(auto_now_add=True)

    

    def __str__(self) -> str:
        return f"{self.stock_sold}"

    class Meta:
        permissions =[
            ("can_allow_dispatch", "can allow dispatch"),
        ]
        ordering = ["-date"]


class Department(models.Model):
    name = models.CharField(verbose_name="name",max_length=10)
    

class Employee(models.Model):
    name = models.CharField(max_length=10)
    department = models.ForeignKey(Department,on_delete=models.CASCADE)
    


    

InventoryApp/shop/forms.py
from django import forms
from django.contrib.auth.models import AbstractUser

from .models import Stock, Sales


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        exclude = ("shelf_life","date","docs","storage","shelf_life","exp","attendant")

 

class StockAdminForms(forms.ModelForm):
    class Meta:
        model = Stock
        exclude = ("docs","storage","shelf_life","exp","attendant")

class SalesAdminForms(forms.ModelForm):
    class Meta:
        model = Sales
        fields = "__all__"

InventoryApp/shop/views.py

from typing import Dict
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView,DetailView,ListView,UpdateView
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.views import View
from .models import Stock
from .forms import StockForm
from django.db.models import Q
import datetime
# Create your views here.


# @method_decorator(login_required(redirect_field_name="index/",login_url="/login/"),name="dispatch")
class IndexView(TemplateView):
    template_name = "index.html"

class Dashboard(TemplateView):
    template_name = "shop/dashboard.html"

class StockList(ListView):
    template_name = "shop/shop_list.html"
    model = Stock
    paginate_by = 50
    #queryset = Stock.objects.all()
    context_object_name = "shop_lists"

class StockDetail(DetailView):
    template_name = "shop/shop_detail.html"
    model = Stock
    context_object_name = "shop_detail"

class StockCreate(LoginRequiredMixin,CreateView):
    model = Stock
    form_class = StockForm
    template_name = "shop/stock_form.html"
    success_url = reverse_lazy("shop:detail-page")
    

    def get_initial(self) -> Dict:
        initial = super().get_initial()
        initial["attendant"]= self.request.user
        initial["status"] = "pending"
        return initial
    def form_valid(self, form) -> HttpResponse:
        form.instance.attendant = self.request.user
        return super().form_valid(form)

  
class StockUpdate(UpdateView):
    model = Stock
    template_name = "shop/shop_update.html"
    form_class = StockForm
    success_url = reverse_lazy("shop:detail-page")


class Timer(View):
    def get(self,request):
        timer = datetime.datetime.now()
        return render(request,"partials/timer-tag.html",{"timer":timer})

class Pdfs(View):
    def get(self,request):
        obj = Stock.objects.all().only("product_name","docs")
        print(obj.values())

        return render(request,"partials/pdfs.html",{"obj":obj})


        
def StockLogout(request):
    logout(request)

def search_product(request):
    q = request.POST["name"]
    print(q)
    if q is not None or q != "":
        q_results = Stock.objects.filter(Q(product_name__icontains=q) | Q(status__icontains=q))
        print(q_results)
        return render(request,"partials/search-results.html",{"q_results":q_results})


    

InventoryApp/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <script src="https://unpkg.com/htmx.org@1.7.0"
    integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo"
    crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}" />
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}" />
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="manifest" href="{% static 'img/site.webmanifest' %}" />
</head>


<body  hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <style>
    h2{
      font-size: 25px;
      font-weight: 600;
      color: #000000;
      margin: auto 20px;
    }
    h2 span{
      color: goldenrod;
    }
    h3{
      margin: auto 10px;
    }

  </style>
  <section>
    <div class="status-bar">
      <h2>Atlantic <span>Logistics</span></h2>
      {% if request.user.is_authenticated %}
      <h3 >{{request.user.username}}</h3>
      {% endif %}
      {% include "partials/timer-tag.html" %}
      <a href="% url 'shop:logout-page' %}"> <i class="fa fa-sign-out"></i> logout</a>
  </section>
  <section>
    <div class="contents">
      <div class="nav-links">
        {% include 'partials/nav-links.html' %}
      </div>
      <div class="main">
        {% block main %} {% endblock main %}
      </div>
    </div>

  </section>
  <script src="{% static 'js/min.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>
  <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'; //insert csrf token when performing AJAX request 
    })
  </script>
</body>

</html>

InventoryApp/templates/shop/dashboard.html
{% extends "shop/base.html" %}
{% block title %} <title>dashboard</title> {% endblock title %}
{% block task-bar %} <div class="task-bar"> </div> {% endblock task-bar %}

{% block main %}

{% endblock main %}

InventoryApp/templates/shop/pdf.html
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Title</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Stock Details </p>
            </div>
        <div>
        <div class='details'>
            Product Name: {{product_name}} <br/>
            Net  weight: {{net_weight}}  <br/>
            Quantity: {{qty}}  <br/>
            Date: {{date}}  <br/>
            Isle: {{isle}}  <br/>
            Tags: {{tags}}  <br/>
            Storage: {{storage}}  <br/>
            Shelf Life: {{shelf_life}}  <br/>
            Expiry date: {{exp}}  <br/>
            Attendant: {{attendant}}  <br/>
            Status: {{status}}  <br/>
            <hr class='hrItem' />
        </div>
    </div>
    </body>
</html>
```

InventoryApp/templates/shop/shop_detail.html
{% extends "shop/base.html" %} {% block title %}
{% block main%}
<div class="container-fluid" hx-swap="outerHTML" hx-target="#container-fluid"  id="container-fluid">
  <div class="row">
    <div class="col">
      <label>Product Name</label>
    </div>
    <div class="col-6">{{shop_detail.product_name}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Net weight</label>
    </div>
    <div class="col-6">{{shop_detail.net_weight}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Quantity</label>
    </div>
    <div class="col-6">{{shop_detail.qty}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Date</label>
    </div>
    <div class="col-6">{{shop_detail.date}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Isle</label>
    </div>
    <div class="col-6">{{shop_detail.isle}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Tags</label>
    </div>
    <div class="col-6">{{shop_detail.tags}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Storage</label>
    </div>
    <div class="col-6">{{shop_detail.storage}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Shelf Life</label>
    </div>
    <div class="col-6">{{shop_detail.shelf_life}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Handler</label>
    </div>
    <div class="col-6">{{shop_detail.attendant}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Status</label>
    </div>
    <div class="col-6">{{shop_detail.status}}</div>
  </div>

  <div class="row">
    <div class="col">
      <label>Document</label>
    </div>
    {% if shop_detail.docs.url %}
    <div class="col-6">
      <a href="{{shop_detail.docs.url}}">Download</a>
    </div>
    {% else %}
    <div class="col-6">
      <h3>No docs</h3>
    </div>
    {% endif %}
  </div>
  <button hx-get="{% url 'shop:update-page' shop_detail.id %}" class="btn btn-primary">click to edit</button>
</div>
{% endblock main %} 


InventoryApp/templates/shop/shop_list.html
{% extends "shop/base.html" %}

{% load static %}

{% block main %}
    <section class="content" style="padding-top: 30px;">
        <table class="table table-striped table-hover table-bordered border-primary">
            <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Product</th>
                  <th scope="col">weight (t)</th>
                  <th scope="col">Quantity / unit </th>
                  <th scope="col">date</th>
                  <th scope="col">isle</th>
                  <th scope="col">tags</th>
                  <th scope="col">storage</th>
                  <th scope="col">shelf life</th>
                  <th scope="col">Expiry</th>
                  <th scope="col">Attendant</th>
                  <th scope="col">status</th>
                  <th scope="col">docs</th>
                </tr>
              </thead>
              <tbody>
                {% for shop_list in shop_lists %}
                <tr id="row" data-href="{% url 'shop:detail-page' shop_list.id %}">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{shop_list.product_name}}</td>
                    <td>{{shop_list.net_weight}}</td>
                    <td>{{shop_list.qty}}</td>
                    <td>{{shop_list.date}}</td>
                    <td>{{shop_list.isle}}</td>
                    <td>{{shop_list.tags}}</td>
                    <td>{{shop_list.storage}}</td>
                    <td>{{shop_list.shelf_life}}</td>
                    <td>{{shop_list.exp}}</td>
                    <td>{{shop_list.attendant}}</td>
                    <td>{{shop_list.status}}</td>
                    {% if shop_list.docs %}
                    <td><p>present</p></td>
                    {% else %}
                    <td><p>unavailabe</p></td>
                    {% endif %}
                  </tr>
                  {% endfor %}
              </tbody>
            
        </table>
    </section>
    <footer>
      <div class="pagination justify-content-center">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    </footer>

{% endblock main %}

InventoryApp/templates/shop/shop_update.html

{% block main %}

<div class="container" >
<form hx-put="{% url 'update-page'  %}" action="." method="post">
    {% if messages %}
    {% for message in messages %}
        <div class="text-center alert alert-{{ message.tags }}">
            {{ message|safe }}
        </div>
    {% endfor %}
    {% endif %}
    
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group col-md-6 mb-3">
        {{ form.product_name.errors }}
        <label for="{{ form.product_name.id_for_label }}">Product Name:</label>
        <div class="row">{{ form.product_name }}</div>
    </div>

    <div class="form-group col-md-6 mb-3">
        {{ form.net_weight.errors }}
        <label for="{{ form.net_weight.id_for_label }}">Net weight:</label>
        <div class="row">{{ form.net_weight }}</div>
    </div>

    <div class="form-group col-md-6 mb-3">
        {{ form.qty.errors }}
        <label for="{{ form.qty.id_for_label }}">Quantity:</label>
        <div class="row">{{ form.qty }}</div>
    </div>

    <div class="form-group col-md-6 mb-3">
        {{ form.tags.errors }}
        <label for="{{ form.isle.id_for_label }}">Tags:</label>
        <div class="row">{{ form.tags }}</div>
    </div>

    <div class="form-group col-md-6 mb-3">
        {{ form.isle.errors }}
        <label for="{{ form.isle.id_for_label }}">Isle:</label>
        <div class="row">{{ form.isle }}</div>
    </div>
    <button type="submit" class="btn btn-primary mb-3">submit</button>
</form>
</div>
{% endblock main %}

InventoryApp/templates/shop/stock_form.html
{% extends "shop/base.html" %}
{% block middle %}

<div class="container">
<form action="." method="post">
    
    {% if messages %}
    {% for message in messages %}
        <div class="text-center alert alert-{{ message.tags }}">
            {{ message|safe }}
        </div>
    {% endfor %}
    {% endif %}
    
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group col-md-6 mb-3">
        {{ form.product_name.errors }}
        <label for="{{ form.product_name.id_for_label }}">Product Name:</label>
        <div class="row">{{ form.product_name }}</div>
    </div>

    <div class="form-group col-md-6 mb-3">
        {{ form.net_weight.errors }}
        <label for="{{ form.net_weight.id_for_label }}">Net weight:</label>
        <div class="row">{{ form.net_weight }}</div>
    </div>

    <div class="form-group col-md-6 mb-3">
        {{ form.qty.errors }}
        <label for="{{ form.qty.id_for_label }}">Quantity:</label>
        <div class="row">{{ form.qty }}</div>
    </div>

    <div class="form-group col-md-6 mb-3">
        {{ form.tags.errors }}
        <label for="{{ form.isle.id_for_label }}">Tags:</label>
        <div class="row">{{ form.tags }}</div>
    </div>

    <div class="form-group col-md-6 mb-3">
        {{ form.isle.errors }}
        <label for="{{ form.isle.id_for_label }}">Isle:</label>
        <div class="row">{{ form.isle }}</div>
    </div>
    <button type="submit" class="btn btn-primary mb-3">submit</button>
</form>
</div>
{% endblock middle %}